### ISSUE TITLE
System wide Light mode does not allow changing the context menu color.

### ISSUE THREAD

**Issue by Kevin64** [Aldaviva/DarkNet#5]
Hi, thanks for your work on this library.

I've tested your lib on my WinForms project and, when the system is in dark mode, the contexts menus change correctly inside the program (I have an in-app theme switcher). But when using Windows in light mode, the contexts menus are always light, regardless of the theme setting. I attached some pictures below to demonstrate the issue in your demo. Thanks!

![oUiQUTsSm9](https://user-images.githubusercontent.com/1903028/222545599-e0f118e0-efae-4fe6-8fe9-e9cb85286d4c.png)
![wLL5laJvZi](https://user-images.githubusercontent.com/1903028/222545607-b9c2d850-3113-40ef-abbc-14da4dfbd25c.png)
![8Qt9xWaoBs](https://user-images.githubusercontent.com/1903028/222545618-9907aba4-4205-4959-99bf-057e03048366.png)
![JMWdcbVi0t](https://user-images.githubusercontent.com/1903028/222546139-13bfcd31-a407-4c2b-971b-0c04638f9dd6.png)
![Ce2tuqQTwM](https://user-images.githubusercontent.com/1903028/222546146-433ad66c-d39e-44d8-bde0-051def46a306.png)
![vjWMcDEyRK](https://user-images.githubusercontent.com/1903028/222546152-53f538de-fc90-45e9-ae37-0f195b03d75c.png)

**Comment by Aldaviva** [comment]
Hi @Kevin64 ,

Thank you for the helpful report and screenshots. I thought I had tested this scenario, but I will reproduce it and figure out what's going on.

**Comment by Aldaviva** [comment]
I think I figured it out. Here's an updated [library](https://github.com/Aldaviva/DarkNet/files/10880225/Debug.zip) and [Forms demo](https://github.com/Aldaviva/DarkNet/files/10878190/darknet.zip) which seem to make the context menus always match the app theme, even when the system theme is Light and the app theme is Dark.

Please give it a quick look and let me know if it works properly for you as well.

**Comment by Kevin64** [comment]
Hi man, thanks for the response!
I've tested your updated library, and it works correctly now. 😁
Can you update the NuGet package, please?

**Comment by Aldaviva** [comment]
[DarkNet 2.1.1](https://www.nuget.org/packages/DarkNet/2.1.1) published on NuGet Gallery.
